
logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

spring:
  thymeleaf:
    suffix: .html
    cache: false
    prefix: classpath:templates/


  mvc:
    view:
      suffix: .html
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bookbell
    username: root
    password: 5199
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
    sql.init.mode: always

  data.rest:
     base-path: /api
     detection-strategy: annotated

---
spring:
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: always


  devtools:
    livereload:
      enabled: true

  web:
    resources:
      static-locations: classpath:templates/
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 554902514192-au1haeci8bc3hgtdf1bl6hnabuik1kug.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "http://localhost:8080/login/oauth2/code/google"
            scope:
              - email
              - profile


          naver:
            client-id: UpSrUewon8QXWPdDB93G
            client-secret: _EPS0YOhpJ
            redirect-uri:  "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - email
              - nickname
              - age
            client-name: Naver

          kakao:
            client-id: 841bf57e02fe486fe15dfc6042a61b66
            client-secret: QBks46Z4YNjGIPC9C7MkbwOtyVGE8dJc
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope:
              - profile
              - account_email

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri :  https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: kakao_account
  config:
    activate:
      on-profile: testdb
      datasource:
        url: jdbc:h2:./bookbell
        driverClassName: org.h2.Driver
      sql.init.mode: always




